spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: order
          uri: lb://RESTAURANT-ORDER
          predicates:
            - Path=/order/**
          filters:
            - name: Hystrix
              args:
                name: order
                fallbackUri: forward:/fallback/orderFallback
        - id: kitchen
          uri: lb://RESTAURANT-KITCHEN
          predicates:
            - Path=/kitchen/**
          filters:
            - name: Hystrix
              args:
                name: kitchen
                fallbackUri: forward:/fallback/kitchenFallback